### ISSUE TITLE
Tradition (Druid) has invalid prerequisite in data

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [elyukai/optolith-client#1237]
## Describe the bug
The data entry for the druid traditions (SA_346) has a prerequisite that references DISADV_8 which does not exits in the data. 
 
## To Reproduce
Get the latest DEV version from optolith-data and have a look at the special abilities.

## Expected behavior
The correct reference should be ADV_7 according to the rule wiki (https://ulisses-regelwiki.de/druiden.html).
The `active: false` is correct as it is.

## Screenshots
```yaml 
- id: SA_346
# name: Tradition (Druiden)
  cost: 125
  max: 1
  activatablePrerequisites:
    - id: ADV_50
      active: true
    - id: DISADV_8
      active: false
  gr: 28
```

## Environment
Latest version of the dev branch.

## Additional context
none
