### ISSUE TITLE
"Untreu" (disadvantage) name contains levels

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [elyukai/optolith-client#1238]
## Describe the bug
The DISADV_81 "Untreu" containes the possible levels (I-II) as part of the name. 

## To Reproduce
Look at the disadvantage list in the data

## Expected behavior
Remove the level part of the name:
```yaml
- id: DISADV_81
  name: "Untreu"
  rules: |
    Die Heldin erhält bei Proben auf *Willenskraft (Betören widerstehen)* eine Erschwernis von 1 pro Stufe der Sonderfertigkeit.
  src:
    - id: US25213
      firstPage: 154
```
## Screenshots
```yaml
- id: DISADV_81
  name: "Untreu I-II"
  rules: |
    Die Heldin erhält bei Proben auf *Willenskraft (Betören widerstehen)* eine Erschwernis von 1 pro Stufe der Sonderfertigkeit.
  src:
    - id: US25213
      firstPage: 154
```

## Environment
Latest version of the data on DEV-Branch

## Additional context
none
