### ISSUE TITLE
Spelling error in Tradition (Levthankult)" SA_1187

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [elyukai/optolith-client#1247]
**Describe the bug**
"rules" filed contains invalid name of skill "Sinnenschärfe" in "Wohlgefällige Talente"

**To Reproduce**
Look at the latest DEV repository.

**Expected behavior**
Name should be "Sinnesschärfe"

**Screenshots**
```yaml
- id: SA_1187
  name: "Tradition (Levthankult)"
  rules: |
    - Eingeschränkte Segnungen: Folgende Segnungen kann der Levthangeweihte nicht anwenden: Eidsegen, Schutzsegen, Weisheitssegen.
    - *Incubus*: Schläft der Levthangeweihte mit einem anderem Kulturschaffenden, so erhält er in der nächsten Regenerationsphase +1 LeP und +1 KK für die nächsten 24 Stunden. Die Person, mit der er geschlafen hat, erleidet hingegen bei der nächsten Regenerationsphase einen Abzug von 1 LeP und verliert für 24 Stunden 1 Punkt KK.
    - Ein Levthangeweihter muss sich an den Moralkodex (Prinzipientreue) halten (siehe 161). Die Wahl des Nachteils ist Voraussetzung, wenn der Spieler einen Geweihten der Kirche spielen will.
    - Wohlgefällige Talente: Betören, Einschüchtern, Gaukeleien, Körperbeherrschung, Kraftakt, Menschenkenntnis, Musizieren, Sinnenschärfe, Tierkunde, Überreden, Zechen
    - Leiteigenschaft der Tradition ist Charisma.
  src:
    - id: US25213
      firstPage: 161
      lastPage: 162
```
**Additional context**
none
